Repository iiiiive/nbcamp-ios, pull requests merged in 2023-08, with the labels that each got.

#18 [add] #15 글쓰기 화면 구현
  NBCamp/Presentation/Write/Storyboard/Write.storyboard
Labels: :blush: aera

#17 Seojin 6
  NBCamp/Presentation/Profile/Storyboard/Profile.storyboard
Labels: :blush: seojin

#16 Hyunwoo 4
  NBCamp.xcodeproj/project.pbxproj
  NBCamp/Model/post.swift
  NBCamp/Model/postImage.swift
  NBCamp/Presentation/Community/Storyboard/Community.storyboard
  NBCamp/Presentation/Community/ViewController/CommunityViewController.swift
  NBCamp/Presentation/Community/ViewController/boardCell.swift
  NBCamp/Presentation/Community/ViewController/postViewCell.swift
Labels: :blush: hyeonwoo

#23 [PR] Yujin-8
  NBCamp.xcodeproj/project.pbxproj
  NBCamp/Info.plist
  NBCamp/Model/Mock.swift
  NBCamp/Model/User.swift
  NBCamp/Presentation/History/Storyboard/History.storyboard
  NBCamp/Presentation/History/ViewController/HistoryViewController.swift
  NBCamp/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  NBCamp/Resource/Assets.xcassets/AppIcon.appiconset/iiiiive.png
  NBCamp/Resource/Assets.xcassets/Image/Contents.json
  NBCamp/Resource/Assets.xcassets/Image/launch.imageset/Contents.json
  NBCamp/Resource/Assets.xcassets/Image/launch.imageset/launch_any.png
  NBCamp/Resource/Assets.xcassets/Image/launch.imageset/launch_dark.png
  NBCamp/Resource/Assets.xcassets/Image/launch.imageset/launch_light.png
  NBCamp/Resource/Assets.xcassets/Palette/Contents.json
  NBCamp/Resource/Assets.xcassets/Palette/nbcAccentColor.colorset/Contents.json
  NBCamp/Resource/Assets.xcassets/Palette/nbcBackgroundColor.colorset/Contents.json
  NBCamp/Resource/Assets.xcassets/Palette/nbcPrimaryColor.colorset/Contents.json
  NBCamp/Resource/Assets.xcassets/Palette/nbcSecondaryColor.colorset/Contents.json
  NBCamp/Resource/Assets.xcassets/Palette/nbcSurfaceColor.colorset/Contents.json
  NBCamp/Resource/Assets.xcassets/Palette/nbcTertiaryColor.colorset/Contents.json
  NBCamp/Resource/Assets.xcassets/Palette/nbcTintColor.colorset/Contents.json
  NBCamp/Resource/Font/Pretendard-Black.ttf
  NBCamp/Resource/Font/Pretendard-Bold.ttf
  NBCamp/Resource/Font/Pretendard-ExtraBold.ttf
  NBCamp/Resource/Font/Pretendard-ExtraLight.ttf
  NBCamp/Resource/Font/Pretendard-Light.ttf
  NBCamp/Resource/Font/Pretendard-Medium.ttf
  NBCamp/Resource/Font/Pretendard-Regular.ttf
  NBCamp/Resource/Font/Pretendard-SemiBold.ttf
  NBCamp/Resource/Font/Pretendard-Thin.ttf
  NBCamp/Resource/LaunchScreen.storyboard
  NBCamp/Utility/.gitkeep
  NBCamp/Utility/ColorManager.swift
Labels: :blush: yujin
